imports:
    - { resource: tables.yml }

services:
    mot.sudoku.controller.mot_sudoku_acp:
        class: mot\sudoku\controller\mot_sudoku_acp
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '@log'
            - '@pagination'
            - '@ext.manager'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%mot.sudoku.tables.mot_sudoku_classic%'
            - '%mot.sudoku.tables.mot_sudoku_gamepacks%'
            - '%mot.sudoku.tables.mot_sudoku_ninja%'
            - '%mot.sudoku.tables.mot_sudoku_samurai%'
            - '%mot.sudoku.tables.mot_sudoku_stats%'

    mot.sudoku.mot_sudoku_main:
        class: mot\sudoku\controller\mot_sudoku_main
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@pagination'
            - '@ext.manager'
            - '@request'
            - '@template'
            - '@user'
            - '%core.root_path%'
            - '%mot.sudoku.tables.mot_sudoku_classic%'
            - '%mot.sudoku.tables.mot_sudoku_fame%'
            - '%mot.sudoku.tables.mot_sudoku_fame_month%'
            - '%mot.sudoku.tables.mot_sudoku_fame_year%'
            - '%mot.sudoku.tables.mot_sudoku_games%'
            - '%mot.sudoku.tables.mot_sudoku_ninja%'
            - '%mot.sudoku.tables.mot_sudoku_samurai%'
            - '%mot.sudoku.tables.mot_sudoku_stats%'
            - '@mot.sudoku.functions'

    mot.sudoku.listener:
        class: mot\sudoku\event\mot_sudoku_listener
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@language'
            - '@template'
            - '@user'
            - '@mot.sudoku.functions'
            - '%mot.sudoku.tables.mot_sudoku_fame%'
            - '%mot.sudoku.tables.mot_sudoku_fame_month%'
            - '%mot.sudoku.tables.mot_sudoku_fame_year%'
            - '%mot.sudoku.tables.mot_sudoku_games%'
            - '%mot.sudoku.tables.mot_sudoku_stats%'
        tags:
            - { name: event.listener }

    mot.sudoku.functions:
        class: mot\sudoku\includes\mot_sudoku_functions
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@language'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%mot.sudoku.tables.mot_sudoku_fame%'
            - '%mot.sudoku.tables.mot_sudoku_fame_month%'
            - '%mot.sudoku.tables.mot_sudoku_fame_year%'

    mot.sudoku.cron.task.mot_sudoku_reward:
        class: mot\sudoku\cron\task\mot_sudoku_reward
        arguments:
            - '@config'
            - '@ext.manager'
            - '@mot.sudoku.functions'
        calls:
            - [set_name, [cron.task.mot_sudoku_reward]]
        tags:
            - { name: cron.task }
